POST  http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###
post http://localhost:8080/api/auth/logout
Content-Type: application/json

{
   "refreshToken": "6f0a6919-9244-400c-b490-ca77ae827ba3"
}

###
GET http://localhost:8080/api/test/public
Content-Type: application/json

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "mario",
  "password": "password123",
  "email": "mario@example.com"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "mario",
  "password": "password123"
}

###
GET http://localhost:8080/api/test/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MDE4MDU2MywiZXhwIjoxNzYwMTgyMzYzfQ.aAUv63DyUGSu5lEWN9RaY5gmHBllIHTYE0R_u2e3-_Y

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}
###
POST http://localhost:8080/api/auth/log